### ISSUE TITLE
Faulty documentation on reading configuration from `pyproject.toml`

### ISSUE THREAD

**Issue by FynnFreyer** [entangled/entangled.py#51]
Docs give the following example for `pyproject.toml` content:

```toml
[[tools.entangled]]
version = "2.0"
watch_list = ["docs/**/*.md"]
```

This doesn't work, because the double brackets turn the entangled config from a table into a list.
They are however needed when configuring languages with `[[tool.entangled.languages]]`.

## Reproduce/Verify

For testing, put the following snippets in a `pyproject.toml` file and tangle something.

### Fails

These don't work for me:

Config is a list, not a dict.

```toml
[[tool.entangled]]
version = '2.0'

[[tool.entangled.languages]]
name = 'SomeLang'
identifiers = ['some']
comment = { open = '//' }
```

> Expected <class 'entangled.config.Config'>, got: [{'version': '2.0', 'watch_list': ['lit/**/*.md'], 'ignore_list': ['**/README.md'], 'languages': [{'name': 'SomeLang', 'identifiers': ['some'], 'comment': {'open': '//'}}]}]

Languages is a dict, not a list.

```toml
[tool.entangled]
version = '2.0'

[tool.entangled.languages]
name = 'SomeLang'
identifiers = ['some']
comment = { open = '//' }
```

> Expected list[entangled.config.language.Language], got: {'name': 'SomeLang', 'identifiers': ['some'], 'comment': {'open': '//'}}

### Works

Config is a dict, languages is a list.

```toml
[tool.entangled]
version = '2.0'

[[tool.entangled.languages]]
name = 'SomeLang'
identifiers = ['some']
comment = { open = '//' }
```
